// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7qLiMCx4nxVQOrzXq8MEe0IW5pfNR65g',
    appId: '1:673439835479:web:f09ecffa6d9841a1d9ca12',
    messagingSenderId: '673439835479',
    projectId: 'nikahready-e5e13',
    authDomain: 'nikahready-e5e13.firebaseapp.com',
    storageBucket: 'nikahready-e5e13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpVsc3fCixVg66XpBOQ1kUz1UeSGznW4',
    appId: '1:673439835479:android:1a1b147defcc05e7d9ca12',
    messagingSenderId: '673439835479',
    projectId: 'nikahready-e5e13',
    storageBucket: 'nikahready-e5e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-n_5srYWAK8Y4Evq4cShd0cX5ZE1SC2k',
    appId: '1:673439835479:ios:d8f5ce37b9a357dfd9ca12',
    messagingSenderId: '673439835479',
    projectId: 'nikahready-e5e13',
    storageBucket: 'nikahready-e5e13.firebasestorage.app',
    iosBundleId: 'com.example.nikahready',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-n_5srYWAK8Y4Evq4cShd0cX5ZE1SC2k',
    appId: '1:673439835479:ios:d8f5ce37b9a357dfd9ca12',
    messagingSenderId: '673439835479',
    projectId: 'nikahready-e5e13',
    storageBucket: 'nikahready-e5e13.firebasestorage.app',
    iosBundleId: 'com.example.nikahready',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7qLiMCx4nxVQOrzXq8MEe0IW5pfNR65g',
    appId: '1:673439835479:web:c471f17cbe677a66d9ca12',
    messagingSenderId: '673439835479',
    projectId: 'nikahready-e5e13',
    authDomain: 'nikahready-e5e13.firebaseapp.com',
    storageBucket: 'nikahready-e5e13.firebasestorage.app',
  );
}
